[tool.poetry]
name = "eagleeye"
version = "0.1.2"
description = "Observing mice from the beginning till the end 🦅"
authors = ["Michael Blaß <m.blass@uke.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.3.2"
pandas = "^2.2.1"
arviz = "^0.22.0"
altair = "^5.5.0"
streamlit = "1.47.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pylint = "^3.1.0"
ipykernel = "^6.30.0"
ruff = "^0.12.7"
virtualenv-pyenv = "^0.5.0"
pytest = "^8.4.1"
mypy = "^1.17.0"
pandas-stubs = "^2.3.0.250703"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]

[[tool.mypy.overrides]]
module = "eagleeye.utils"
disallow_untyped_calls = false

[[tool.mypy.overrides]]
module = "eagleeye.preprocessing"
disallow_untyped_calls = false
disable_error_code = "attr-defined"

[[tool.mypy.overrides]]
module = "eagleeye.widgets"
disable_error_code = "arg-type"
